config/routes.rb
HoowenwareDev::Application.routes.draw do
  root "pages#index"
  
  resources :files
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :trips do    
    member do
      get 'add_photo', as: 'add_photo_to'
      get 'rsvp', as: 'rsvp_to'
      get 'cancel'
      get 'reactivate'
      get 'preview_invitation'
    end

    resources :invitations, only: [:new, :create]
    get "invitations/facebook" => 'invitations#facebook',
        :as => 'facebook_invitation'
    get "invitations/google" => 'invitations#google',
        :as => 'google_invitation'


    resources :polls do
      member do
        get 'dates'
        get 'locations'
      end
    end
    
    resources :posts, only: [:create]
    resources :activities
    resources :transportations

  end

  resources :groups do
    member do
      get 'deactivate'
      get 'reactivate'
    end

    resources :memberships, only: [:new, :create]
    
    get "memberships/:email/approve" => 'memberships#approve', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/},
        :as => 'approve_membership'

    get "memberships/:email/pend" => 'memberships#pend', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'pend_membership'

    get "memberships/:email/promote" => 'memberships#promote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'promote_membership'

    get "memberships/:email/demote" => 'memberships#demote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'demote_membership'

    delete "memberships/:email/remove" => 'memberships#remove', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'remove_membership'
  end
  
  resources :users, only: [:create, :show, :edit, :update] do
    resources :web_links, only: [:new, :create, :destroy]
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  validates :email,                 :presence => true
  validates_uniqueness_of :email,   :scope => :group_id

  belongs_to :group
  belongs_to :user
  has_many :permissions, as: :thing
  
  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: "view", user_id: user.id })
  end

  def get_user
    @user = User.find_by(:email=> self.email)
    return @user
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_group
  before_action :set_membership, only: [:approve, :pend, :promote, :demote,
                                        :remove]
  before_filter :authenticate_user!

  def new
    #set_group
    @membership = @group.memberships.build
    @is_group_admin = is_group_admin?(current_user)
  end

  def create
    #set_group
    @membership = @group.memberships.build(membership_params)
    if is_group_admin?(current_user) or current_user.is_admin?
      if @membership.save
        flash[:notice] = "Member has been added to this group."
        redirect_to group_path(@group)
      else
        flash[:alert] = "Duplicate members cannot be added to group."
        redirect_to group_path(@group)
      end
    else
      flash[:notice] = "You must be a group admin to do that."
      redirect_to group_path(@group)
    end
  end

  def approve
    if is_group_admin?(current_user) or current_user.is_admin?
      @membership.update(is_active: true, last_updated_by: current_user.id)
      flash[:notice] = "Membership has been activated."
      redirect_to group_path(@group)
    else
      flash[:notice] = "You must be a group admin to do that."
      redirect_to group_path(@group)
    end
  end

  def pend
    if is_group_admin?(current_user) or current_user.is_admin?
      if current_user.email  == @membership.email
        flash[:alert] = "Error, you can't set yourself to pending."
        redirect_to group_path(@group)
      else
        @membership.update(is_active: false, last_updated_by: current_user.id)

        flash[:notice] = "Membership has been suspended."
        redirect_to group_path(@group)
      end
    else
      flash[:notice] = "You must be a group admin to do that."
      redirect_to group_path(@group)
    end
  end

  def promote
    if is_group_admin?(current_user) or current_user.is_admin?
      @membership.update(is_active: true, is_admin: true, last_updated_by: current_user.id)

      flash[:notice] = "Membership has been upgraded to group administrator."
      redirect_to group_path(@group)
    else
      flash[:notice] = "You must be a group admin to do that."
      redirect_to group_path(@group)
    end
  end

  def demote
    if is_group_admin?(current_user) or current_user.is_admin?
      if current_user.email  == @membership.email
        flash[:alert] = "Error, you can't demote yourself."
        redirect_to group_path(@group)
      else
        @membership.update(is_admin: false, last_updated_by: current_user.id)

        flash[:notice] = "Membership has been set to normal user."
        redirect_to group_path(@group)
      end
    else
      flash[:notice] = "You must be a group admin to do that."
      redirect_to group_path(@group)
    end
  end

  def remove
    #set_membership
    if is_group_admin?(current_user) or current_user.is_admin?
      if current_user.email  == @membership.email
        flash[:alert] = "Error, you can't demote yourself."
        redirect_to group_path(@group)
      else
        @membership.destroy
        flash[:notice] = "Member has been removed from group."
        redirect_to group_path(@group)
      end
    else
      flash[:notice] = "You must be a group admin to do that."
      redirect_to group_path(@group)
    end
  end


  private
    def membership_params
      params.require(:membership).permit(:email)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end

    def set_membership
      @membership = @group.memberships.find_by email: params[:email]
    end

    def is_group_admin?(user)
      if user
        if @group.memberships.find_by(:email => user.email, :is_admin => true)
          return true
        end
      end
      return false
    end
end

app/views/memberships/_active.html.erb
<% @group.memberships.each do |member| %>
  <% if member.email %>
  <div class="member">
    <% if member.is_active?%>
      <%= member.email %>
      <%if @group_admin && member.email != current_user.email or current_user.is_admin? %>
        <% if member.is_active?%>
        | <%= link_to "deactivate", group_pend_membership_path(@group, member.email) %>
        <% else %>
        | <%= link_to "approve", group_approve_membership_path(@group.id, member.email) %>
        <% end %>
        <% if member.is_admin? %>
        | <%= link_to "demote", group_demote_membership_path(@group, member.email) %>
        <% else %>
        | <%= link_to "promote", group_promote_membership_path(@group, member.email) %>
        <% end %>
        | <%= link_to "remove", group_remove_membership_path(@group, member.email),
                      method: :delete,
                      data: { confirm:
                              "Are you sure you want to remove member from this group?"
                            }
          %>
      <% end %>
    <% else %>
      <%if @group_admin or current_user.is_admin? %>
        <%= member.email %>
        <%if @group_admin && member.email != current_user.email or current_user.is_admin? %>
        <% if member.is_active?%>
        | <%= link_to "deactivate", group_pend_membership_path(@group, member.email) %>
        <% else %>
        | <%= link_to "approve", group_approve_membership_path(@group.id, member.email) %>
        <% end %>
        <% if member.is_admin? %>
        | <%= link_to "demote", group_demote_membership_path(@group, member.email) %>
        <% else %>
        | <%= link_to "promote", group_promote_membership_path(@group, member.email) %>
        <% end %>
        | <%= link_to "remove", group_remove_membership_path(@group, member.email),
                      method: :delete,
                      data: { confirm:
                              "Are you sure you want to remove member from this group?"
                            }
          %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <% end %>
<% end %>

app/views/memberships/_form.html.erb
  <%= form_for [@group, @membership], html: {id: 'add_group_member'} do |f| %>
    <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@membership.errors.count, "error") %> prohibited this member from being added:
      </h4>
      <ul>
        <% @membership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email %>
    <%= f.submit 'Add Member' %>
  <% end %>

app/views/memberships/_list.html.erb
<% @group.memberships.each do |member| %>
  <% if member.email %>
  <div class="member">
    <% if member.is_active?%>
      <%= link_to member.get_user.full_name, user_path(member.get_user) %>
      <%if user_signed_in? %> 
        <% if @group_admin and member.email != current_user.email or current_user.is_admin? %>
          <% if member.is_active?%>
          | <%= link_to "deactivate", group_pend_membership_path(@group, member.email) %>
          <% else %>
          | <%= link_to "approve", group_approve_membership_path(@group.id, member.email) %>
          <% end %>
          <% if member.is_admin? %>
          | <%= link_to "demote", group_demote_membership_path(@group, member.email) %>
          <% else %>
          | <%= link_to "promote", group_promote_membership_path(@group, member.email) %>
          <% end %>
          | <%= link_to "remove", group_remove_membership_path(@group, member.email),
                        method: :delete,
                        data: { confirm:
                                "Are you sure you want to remove member from this group?"
                              }
            %>
        <% end %>
      <% end %>
    <% else %>
      <%if user_signed_in? %> 
        <% if @group_admin and member.email != current_user.email or current_user.is_admin? %>
          <%= mail_to member.email %>
          <%if user_signed_in? and @group_admin && member.email != current_user.email or current_user.is_admin? %>
          <% if member.is_active?%>
          | <%= link_to "deactivate", group_pend_membership_path(@group, member.email) %>
          <% else %>
          | <%= link_to "approve", group_approve_membership_path(@group.id, member.email) %>
          <% end %>
          <% if member.is_admin? %>
          | <%= link_to "demote", group_demote_membership_path(@group, member.email) %>
          <% else %>
          | <%= link_to "promote", group_promote_membership_path(@group, member.email) %>
          <% end %>
          | <%= link_to "remove", group_remove_membership_path(@group, member.email),
                        method: :delete,
                        data: { confirm:
                                "Are you sure you want to remove member from this group?"
                              }
            %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <% end %>
<% end %>