config/routes.rb
HoowenwareDev::Application.routes.draw do
  root "pages#index"
  
  resources :files
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :trips do    
    member do
      get 'add_photo', as: 'add_photo_to'
      get 'rsvp', as: 'rsvp_to'
      get 'cancel'
      get 'reactivate'
      get 'preview_invitation'
    end

    resources :invitations, only: [:new, :create]
    get "invitations/facebook" => 'invitations#facebook',
        :as => 'facebook_invitation'
    get "invitations/google" => 'invitations#google',
        :as => 'google_invitation'


    resources :polls do
      member do
        get 'dates'
        get 'locations'
      end
    end
    
    resources :posts, only: [:create]
    resources :activities
    resources :transportations

  end

  resources :groups do
    member do
      get 'deactivate'
      get 'reactivate'
    end

    resources :memberships, only: [:new, :create]
    
    get "memberships/:email/approve" => 'memberships#approve', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/},
        :as => 'approve_membership'

    get "memberships/:email/pend" => 'memberships#pend', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'pend_membership'

    get "memberships/:email/promote" => 'memberships#promote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'promote_membership'

    get "memberships/:email/demote" => 'memberships#demote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'demote_membership'

    delete "memberships/:email/remove" => 'memberships#remove', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'remove_membership'
  end
  
  resources :users, only: [:create, :show, :edit, :update] do
    resources :web_links, only: [:new, :create, :destroy]
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, :presence => true

  has_many :memberships
  has_many :users, :through => :memberships
  has_many :trips
  has_many :permissions, as: :thing

  scope :viewable_by, ->(user) do
    joins(:permissions).where(permissions: { action: "view", user_id: user.id })
  end

  def to_s
    return self.name
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize_admin!, only: [:deactivate, :reactivate, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :deactivate,
                                    :reactivate, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  before_filter :check_for_cancel, :only => [:create, :update]

  def index
    @groups = Group.order('name ASC')
  end

  def new
    @group = Group.new

  end

  def create
    @group = Group.new(group_params)
    if @group.save
      @membership = @group.memberships.build(email: current_user.email,
                                            is_admin: true,
                                            is_active: true)
      @group.update(is_active: true)
      flash[:notice] = "This group has been created."
      redirect_to @group
    else
      flash[:alert] = "This group has not been created."
      render "new"
    end
  end

  def show
    #set_group
    @membership = @group.memberships.build
    @memberships = Membership.where(group_id: @group.id)
    @group_admin = is_group_admin?(current_user)
  end

  def edit
    #set_group
    if ! is_group_admin?(current_user)
      flash[:alert] = "You cannot edit memberships on this group."
      redirect_to @group
    end
  end

  def update
    #set_group
    if @group.update(group_params)
      flash[:notice] = "This group has been updated."
      redirect_to @group
    else
      flash[:alert] = "This group has not been updated."
      render "edit"
    end
  end

  def deactivate
    @group.update(is_active: false)
    flash[:notice] = "This group has been deactivated."
    redirect_to groups_path
  end

  def reactivate
    @group.update(is_active: true)

    flash[:notice] = "This group has been reactivated."
    redirect_to groups_path

  end

  def destroy
    #set_group
    @group.destroy

    flash[:notice] = "This group has been deleted."
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:name, :description, :group_type, :location,
                                    :avatar, :facebook_url, :meetup_url, :groupme_id)
    end

    def set_group
      @group = Group.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The group you were looking for could not be found."
      redirect_to groups_path
    end

    def check_for_cancel
      if params[:commit] == "Cancel"
        flash[:notice] = "Your changes have been cancelled."
        redirect_to @group
      end
    end
    def is_group_admin?(user)
      if user
        if @group.memberships.find_by(:email => user.email, :is_admin => true)
          return true
        end
      end
      return false
    end
    def authorize_update!
      if !current_user.is_admin? && !is_group_admin?(current_user) && cannot?("edit groups".to_sym, @group)
        if !is_group_admin?(current_user)
          flash[:alert] = "You cannot edit memberships on this group."
          redirect_to group_path(@group)
        end
      end
    end
end

app/views/groups/_active.html.erb
  <% @groups.each do |group| %>
    <% if group.is_active? %>
      <div>
        <%= link_to group.name, group %>
      </div>
      <br />
    <% end %>
  <% end %>

app/views/groups/_form.html.erb
  <%= form_for @group, html: {multipart: true, id: 'new_group_form' } do |f| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h4>
          <%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:
        </h4>
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :name, 'Group Name:' %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :description, 'Group Description:' %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :location, 'Group Location:' %>
      <%= f.text_field :location %>
    </div>
    <div>
      <%= f.label :group_type, 'Group Type:' %>
      <%= f.text_field :group_type %>
    </div>
    <div>
      <%= f.label :avatar, 'Group Avatar:' %>
      <%= f.text_field :avatar %>
    </div>
    <div>
      <%= f.label :facebook_url, 'Facebook Link:' %>
      <%= f.text_field :facebook_url %>
    </div>
    <div>
      <%= f.label :meetup_url, 'Meetup Link:' %>
      <%= f.text_field :meetup_url %>
    </div>
    <div>
      <%= f.label :groupme_id, 'GroupMe ID:' %>
      <%= f.text_field :groupme_id %>
    </div>
    <div>
      <div>
        <% if @group.new_record? %>
          <%= f.submit 'Create'%>
        <% else %>
          <%= f.submit 'Update'%>
        <% end %>
        <%= button_tag "Reset", type: :reset%>
        <%= f.submit "Cancel"%>
      </div>
    </div>
  <% end %>

app/views/groups/_inactive.html.erb
  <% @groups.each do |group| %>
    <% if group.is_active == false %>
      <div>
        <%= link_to group.name, group %>
      </div>
      <br />
    <% end %>
  <% end %>

app/views/groups/edit.html.erb
<h4><%= @group.name %> Settings</h4>
<%= render "form" %>

app/views/groups/index.html.erb
  <div id="active_groups">
    <%= render "active" %>
  </div>
  <% if current_user && current_user.is_admin? %>
  <hr />
  <div id="inactive_groups">
    <h4> Inactive Groups </h4>
    <%= render "inactive" %>
  </div>
  <% end %>

app/views/groups/new.html.erb
  <h3>Create a new Group</h3>
  <div>
    <%= render "form" %>
  </div>

app/views/groups/show.html.erb
  <% page_title(@group.name, "Groups") %>
  <div id="group">
  <h4><%= @group.name %></h4>
  <% if @group.description %>
  <div>
    Desciption:<%= @group.description %>
  </div>
  <% end %>
  <% if @group.group_type %>
  <div>
    Group Type: <%= @group.group_type %>
  </div>
  <% end %>
  <% if @group.location %>
  <div>
    location: <%= @group.location %>
  </div>
  <% end %>
  <% if @group.avatar %>
  <div>
    <%= image_tag @group.avatar %>
  </div>
  <% end %>
  <% if @group.facebook_url %>
  <div>
    Facebook: <%= link_to @group.facebook_url %>
  </div>
  <% end %>
  <% if @group.meetup_url %>
   <div>
    Meetup: <%= link_to @group.meetup_url %>
  </div>
  <% end %>
  <% if @group.groupme_id %>
  <div>
    GroupMeL <%= @group.groupme_id %>
  </div>
  <% end %>
  <hr />

  <strong>Members:</strong>
  <%if user_signed_in? %>
    <% if  @group_admin or current_user.is_admin? %>
    <div>
      <%= render "memberships/form" %>
    </div>
    <% end %>
  <% end %>
  <div>
    <%= render "memberships/list" %>
  </div>
  <hr />
  <%if user_signed_in? %>
    <% if  @group_admin or current_user.is_admin? %>
      <%= link_to "Settings", edit_group_path(@group) %>
      <% if @group.is_active? %>
        <%= link_to "Deactivate this group", deactivate_group_path(@group) %>
      <% else %>
        <%= link_to "Reactivate this group", reactivate_group_path(@group) %>
      <% end %>
        
      <% if current_user && current_user.is_admin? %>
        <%= link_to "Delete This group",
                  group_path(@group),
                  method: :delete,
                  data: { confirm:
                          "Are you sure you want to cancel this group?"
                        }
        %>
      <% end %>
    <% end %>
  <% end %>
  </div>