config/routes.rb
HoowenwareDev::Application.routes.draw do
  root "pages#index"
  
  resources :files
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :trips do    
    member do
      get 'add_photo', as: 'add_photo_to'
      get 'rsvp', as: 'rsvp_to'
      get 'cancel'
      get 'reactivate'
      get 'preview_invitation'
    end

    resources :invitations, only: [:new, :create]
    get "invitations/facebook" => 'invitations#facebook',
        :as => 'facebook_invitation'
    get "invitations/google" => 'invitations#google',
        :as => 'google_invitation'


    resources :polls do
      member do
        get 'dates'
        get 'locations'
      end
    end
    
    resources :posts, only: [:create]
    resources :activities
    resources :transportations

  end

  resources :groups do
    member do
      get 'deactivate'
      get 'reactivate'
    end

    resources :memberships, only: [:new, :create]
    
    get "memberships/:email/approve" => 'memberships#approve', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/},
        :as => 'approve_membership'

    get "memberships/:email/pend" => 'memberships#pend', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'pend_membership'

    get "memberships/:email/promote" => 'memberships#promote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'promote_membership'

    get "memberships/:email/demote" => 'memberships#demote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'demote_membership'

    delete "memberships/:email/remove" => 'memberships#remove', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'remove_membership'
  end
  
  resources :users, only: [:create, :show, :edit, :update] do
    resources :web_links, only: [:new, :create, :destroy]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter, :linkedin,
                                                :google, :yahoo, :windowslive,
                                                :github, :meetup, :dropbox]

  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships
  has_many :trips
  has_many :permissions
  has_many :poll_responses
  has_many :invitations
  has_many :authentications
  has_many :web_links
  
  def to_s
    "#{first_name} #{last_name}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.find_for_facebook_oauth(auth)
    @acct = Authentication.find_for_facebook_oauth(auth)

    where(@acct.slice(:email)).first_or_initialize.tap do |user|
      user.email      = auth.info.email
      user.password   = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name  = auth.info.last_name
      user.avatar     = auth.info.image.split('type=')[0]+'type=large'
      user.save!
      @acct.update(user_id: user.id)
    end
  end

  def self.find_for_google_oauth(auth)
    @acct = Authentication.find_for_google_oauth(auth)

    where(@acct.slice(:email)).first_or_initialize.tap do |user|
      user.email      = auth.info.email
      user.password   = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name  = auth.info.last_name
      user.avatar     = auth.info.image
      user.save!
      @acct.update(user_id: user.id)
    end
  end

  def self.find_for_dropbox_oauth(auth)
    @acct = Authentication.find_for_dropbox_oauth(auth)

    where(@acct.slice(:email)).first_or_initialize.tap do |user|
      user.email      = auth.info.email
      user.password   = Devise.friendly_token[0,20]
      user.first_name = auth.info.name.split(' ')[0]
      user.last_name  = auth.info.name.split(' ')[1]
      user.avatar     = self.gravatar_url(auth.info.email)
      user.save!
      @acct.update(user_id: user.id)
    end
  end


  def has_facebook_acct?
    @acct = self.authentications.where(:provider => 'facebook')
    if @acct.present?
      return true
    end
    return false
  end

  def facebook_acct
    @acct = self.authentications.where(:provider => 'facebook').first!
  end

  def has_google_acct?
    @acct = self.authentications.where(:provider => 'google')
    if @acct.present?
      return true
    end
    return false
  end

  def google_acct
    @acct = self.authentications.where(:provider => 'google').first!
  end

  def has_dropbox_acct?
    @acct = self.authentications.where(:provider => 'dropbox')
    if @acct.present?
      return true
    end
    return false
  end

  def dropbox_acct
    @acct = self.authentications.where(:provider => 'dropbox').first!
  end

  def has_links?
    @links = self.web_links
    if @links.present?
      return true
    end
    return false
  end


  def links
    @links = self.web_links
  end

  private
    # quick method to see what the oauth provider returns
    def self.console_log(oauth_response)
      require 'pp'
      5.times { puts '' }
      pp oauth_response
      5.times { puts '' }
    end

    # gravatar imgage url generator
    def self.gravatar_url(email)
      require 'digest/md5'
      hash = Digest::MD5.hexdigest(email.downcase)
      image_src = "http://www.gravatar.com/avatar/#{hash}?s=300"
      return image_src
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google
    @user = User.find_for_google_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def dropbox
    @user = User.find_for_dropbox_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Dropbox") if is_navigational_format?
    else
      session["devise.dropbox_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  before_action :get_groups, :get_trips, :only => [:show, :update]
  before_action :get_active_groups, :get_membership_ids, :only => [:edit, :update]
  before_filter :authenticate_user!, except: [:show]
  before_filter :check_for_cancel, :only => [:update]


  def show
    #set_user
    @web_link = @user.web_links.build(url: '')
    @groups = @memberships.where(:email => @user.email).map {|x| x.group }
  end

  def edit
    #set_user
  end

  def update
    #set_user
    if @user.update(user_params)
      # This needs to be fixed to remove unselected group
      puts params[:groups]
      if params[:groups]
        params[:groups].each do |id| 
          @group = Group.find(id)
          @membership = @group.memberships.build(email: @user.email, 
                                                is_admin: false,
                                                is_active: false)
          @membership.save
        end
      end

      @user.update(profile_updated: true)

      flash[:notice] = "Your profile has been updated."
      render "show"
    else
      flash[:alert] = "Your profile has not been updated."
      render "edit"
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name,
                                    :gender, :status, :avatar, :zip_code, :mobile_number, 
                                    :skype_id, :dietary_pref, :roommate_pref)
    end
    def set_user
      @user = User.find(params[:id])
   rescue ActiveRecord::RecordNotFound
     flash[:alert] = "The profile you were looking for could not be found."
     redirect_to root_path
    end

    def get_active_groups
      @active_groups = Group.where(is_active: true)
    end

    def get_membership_ids
      @membership_ids = Membership.where(:email => @user.email).map {|x| x.group_id }
    end

    def get_groups
      @memberships = Membership.where(:email => @user.email)
    end

    def get_trips
      @trips = Trip.where(user_id: @user.id)
    end

    def check_for_cancel
      if params[:commit] == "Cancel"
        flash[:notice] = "Your changes have been cancelled."
        redirect_to @user
      end
    end
end

app/views/users/_form.html.erb
  <%= form_for @user, url: user_path(@user), html: { multipart: true, id: 'edit_user_form' } do |f| %>
   <% if @user.errors.any? %>
      <div id="error_explanation">
        <h4>
          <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
        </h4>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <%= f.label :email, 'Email:' %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :first_name, 'First Name:' %>
      <%= f.text_field :first_name, :required => '' %>
    </div>

    <div>
      <%= f.label :last_name, 'Last Name:' %>
      <%= f.text_field :last_name, :required => '' %>
    </div>

    <div>
      <%= f.label :groups, 'Groups:' %>
      <%= select_tag 'groups[]', options_from_collection_for_select(@active_groups, :id, :name, @membership_ids), { :multiple => true, :size => 5 } %>
    </div>

    <div>
      <%= f.label :gender, 'Gender:' %>
      <%= f.select :gender, [['',''], ['male', 'male'], ['female', 'female'], ['transgender', 'transgender']] %>
    </div>

    <div>
      <%= f.label :status, 'Status:' %>
      <%= f.select :status, [['',''], ['single', 'single'], ['married', 'married'],
                            ['divorced', 'divorced'], ['involved', 'involved']] %>
    </div>

    <div>
      <div class="profile-image">
        <%= image_tag @user.avatar, :class => 'edit_profile_img' %>
      </div>
      <%= f.label :avatar, 'Add Photo:' %>
      <%= f.text_field :avatar %>
    </div>

    <div>
      <%= f.label :zip_code, 'Zip Code:' %>
      <%= f.text_field :zip_code %>
    </div>

    <div>
      <%= f.label :mobile_number, 'Mobile No:' %>
      <%= f.text_field :mobile_number %>
    </div>

    <div>
      <%= f.label :skype_id, 'Skype ID:' %>
      <%= f.text_field :skype_id %>
    </div>

    <div>
      <%= f.label :dietary_pref, 'Dietary Preferences:' %>
      <%= f.select :dietary_pref, [['none', 'none'], ['vegan', 'vegan'], ['kosher', 'kosher'],
                                ['vegitarian', 'vegitarian'],['allergnic-free', 'allergnic-free'],
                                ['gluten / casein free', 'gluten / casein free'],
                                ['other', 'other']] %>
    </div>


    <div>
      <%= f.label :roommate_pref, 'Roommate Preferences:' %>
      <%= f.select :roommate_pref, [['none', 'none'], ['single female', 'single female'],
                                    ['single male', 'single male'], ['group females', 'group females'],
                                    ['group males', 'group males']] %>
    </div>

     <div>

        <%= f.submit 'Update'%>
        <%= button_tag "Reset", type: :reset%>
        <%#= button_tag "Skip", type: :reset %>
        <%= f.submit "Cancel"%>
    </div>

  <% end %>
  <hr />

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<div class="container">
  <div>
    <%= image_tag @user.avatar %>
  </div>
  <div>
    <p>
      <%= @user %>, <%= @user.email %>
    </p>
  </div>
  <div>
    <p>Lives in: <%= @user.zip_code %></p>
  </div>

  <hr />
  <% @memberships.each do |membership| %>
    <%=link_to membership.group, group_path(membership.group.id) %>
    <% if ! membership.is_active? %>
    ( pending )
    <% end %>
  <% end %>
  <% if @trips.length > 0 %>
    <h4> <%= "#{@user.first_name}'s" %> Trips</h4>
    <div id="active_trips">
      <strong>Active</strong>
      <%= render "trips/active" %>
    </div>
    <% cancelled_trips = @trips.where(is_active: false) %>
    <% if ! cancelled_trips.empty? %>
    <div id="cancelled_trips">
      <strong>Cancelled</strong>
      <%= render "trips/inactive" %>
    </div>
    <% end %>
  <% end %>
  <div>
  <% if @user.has_links?  %>
    <h4> links: </h4>
    <% @user.links.each do |web_link| %>
      <% if web_link.id %>
        <div>
        <% if user_signed_in? %>
          <% if @user == current_user or current_user.is_admin? %>
            <%= link_to 'Delete' , 
                user_web_link_path(id: web_link.id, user_id: @user.id),
                method: :delete
             %> |
          <% end %>
        <% end %>
        <%= link_to web_link.url, web_link.url, :target => "_blank" %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <% if user_signed_in? %>
    <% if @user == current_user or current_user.is_admin? %>
      <h4> Add your social urls </h4>
      <%= link_to "Add a link", new_user_web_link_path(@user) ,:class=>"btn btn-primary"%>
      <%= link_to "Edit Profile", edit_user_path(@user) ,:class=>"btn btn-success"%>
    <% end %>
  </div>
  <% end %>
</div>