config/routes.rb
HoowenwareDev::Application.routes.draw do
  root "pages#index"
  
  resources :files
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :trips do    
    member do
      get 'add_photo', as: 'add_photo_to'
      get 'rsvp', as: 'rsvp_to'
      get 'cancel'
      get 'reactivate'
      get 'preview_invitation'
    end

    resources :invitations, only: [:new, :create]
    get "invitations/facebook" => 'invitations#facebook',
        :as => 'facebook_invitation'
    get "invitations/google" => 'invitations#google',
        :as => 'google_invitation'


    resources :polls do
      member do
        get 'dates'
        get 'locations'
      end
    end
    
    resources :posts, only: [:create]
    resources :activities
    resources :transportations

  end

  resources :groups do
    member do
      get 'deactivate'
      get 'reactivate'
    end

    resources :memberships, only: [:new, :create]
    
    get "memberships/:email/approve" => 'memberships#approve', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/},
        :as => 'approve_membership'

    get "memberships/:email/pend" => 'memberships#pend', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'pend_membership'

    get "memberships/:email/promote" => 'memberships#promote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'promote_membership'

    get "memberships/:email/demote" => 'memberships#demote', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'demote_membership'

    delete "memberships/:email/remove" => 'memberships#remove', 
        :controller => 'memberships',
        :constraints => { :email => /[^\/]+/ },
        :as => 'remove_membership'
  end
  
  resources :users, only: [:create, :show, :edit, :update] do
    resources :web_links, only: [:new, :create, :destroy]
  end
end

app/helpers/layout_helper.rb
module LayoutHelper

  def bootstrap_version
    # Choose the Bootstrap version you would like to use from the CDN
    "3.1.1"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Hoowenware | Development" %></title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container">
    <div class="row"> 
      <% flash.each do |key, value| %>
  
      <div class='flash center-block alert alert-warning alert-dismissable' style="width:50%" id='<%= key %>'>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= value %>
      </div>
      <% end %>
   </div>
  </div>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Hoowenware", root_path,:class=>"navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        
          <ul class="nav navbar-nav">
            
              <% if !current_user %>
                <li>
                 <%= link_to 'Sign up', new_user_registration_path %>
                </li>
                <li>
                 <%= link_to "Sign in", new_user_session_path %>
                </li>
              <% end %>
            </li>
            <li> <%= link_to "Groups", groups_path %></li>
            <li> <%= link_to "Create a Group", new_group_path %></li>
            <li> <%= link_to "Trips", trips_path %></li>
            <li> <%= link_to "Create a Trip", new_trip_path %></li> 
            <!--<% if ! @home_page %>
              <li>  <%= link_to "Home", root_path %></li>
            <% end %>
          -->
          </ul>
       <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>
            <%= link_to current_user, current_user %> 
          </li>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          </li>
        <% end %>
      </ul>
      </div>
    </div>
  </div>

      <%= yield %>
 
  <script src="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/js/bootstrap.min.js"></script>
  </body>
</html>